### PR TITLE
ONEM-19775: Change customData type from ArrayBuffer to string

### PR DESCRIPTION
**Pull request by jacek-manko-red**

### CODE REVIEW

**Review by zbigniew-holdys-epam — DISMISSED** [review]
Looks good to me!

**Comment by jacek-skiba-red** [comment]
Browser API is maintained by Igalia and Metro, apps (eg. Videoland) are maintained by Metro, so why we need to change on our side custoData argument to DOMString. By default it's not working?

**Comment by jacek-manko-red** [comment]
> Browser API is maintained by Igalia and Metro, apps (eg. Videoland) are maintained by Metro, so why we need to change on our side custoData argument to DOMString. By default it's not working?

Well, good question, but Metro apps are passing it as DOMString... It's not a part of EME specification, so it's not clear what the correct type is

**Comment by jacek-skiba-red** [comment]
> > Browser API is maintained by Igalia and Metro, apps (eg. Videoland) are maintained by Metro, so why we need to change on our side custoData argument to DOMString. By default it's not working?
> 
> Well, good question, but Metro apps are passing it as DOMString... It's not a part of EME specification, so it's not clear what the correct type is

But Metro is paying Igalia for maitanining WPE2.22. Those interfaces should be in sync.

**Comment by jacek-manko-red** [comment]
Lightning version of Videoland is using ArrayBuffer aka BufferSource, so this change is not needed

**Pull request closed without merging**
